#ifndef DEFINES_H
#define DEFINES_H


#define GRID_WIDTH 40
#define GRID_HEIGHT 24
#define GRID_SIZE (GRID_WIDTH * GRID_HEIGHT)

#define MAX_TILE_ACTIONS 1024

#define MAX_BATTLE_MSG_LENGTH 128
#define MAX_BATTLE_EVENTS 32


#endif // DEFINES_H

